name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.0.23
homepage: https://github.com/DinoLeung/TeleDart
author: Dino Leung <dino@330z.net>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0
  http: ^0.12.0+1

dev_dependencies:
  test: ^1.5.3
  build_runner: ^1.2.5
  json_serializable: ^2.0.0

