name: teledart
description: A dart library for interfacing with the Telegram Bot API
version: 0.0.15
homepage: https://github.com/DinoLeung/TeleDart
author: Dino Leung <dino@330z.net>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.1.0
  http: ^0.11.3+17

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.1
  json_serializable: ^1.1.0

