name: teledart
description: A dart library for interfacing with the Telegram Bot API
version: 0.0.10
homepage: https://github.com/DinoLeung/TeleDart
author: dino <dino@330z.net>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  dartson: ">=0.2.0 <0.3.0"
  http: "^0.11.3+16"
#  path: ^1.4.1

# transformers:
# - dartson

dev_dependencies:
  test: ^0.12.0
