name: teledart
description: Telegram bot api framework in Dart
version: 0.0.6
homepage: https://github.com/DinoLeung/TeleDart
author: dino <dino@330z.net>

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  dartson: ">=0.2.0 <0.3.0"
  http: "^0.11.3+16"
#  path: ^1.4.1

transformers:
- dartson

dev_dependencies:
  test: ^0.12.0
