name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.0.28
homepage: https://github.com/DinoLeung/TeleDart
author: Dino Leung <dino@330z.net>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^2.1.0
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.6.1
  build_runner: ^1.2.5
  json_serializable: ^2.1.1
  pedantic: '1.5.0'

